openapi: 3.0.0
info:
  title: AR Invoice Query API
  description: A full-stack application allowing users to input natural language queries to retrieve AR invoice data from a Snowflake database using OpenAI.
  version: 1.0.0
servers:
  - url: https://production-domain.com/api/v1
    description: Production server (deployed on AWS)

paths:
  /invoices/query:
    post:
      summary: Accepts a natural language query, generates an equivalent SQL query, executes it against the database, and returns the top 100 AR Invoices data along with dynamic insights.
      description: The endpoint processes natural language queries, generates corresponding SQL queries, executes them against a Snowflake database, and returns the requested invoices with pagination, sorting, and dynamic insights.
      operationId: queryInvoices
      tags:
        - Invoices
      requestBody:
        description: Natural language query to be processed and executed against the database.
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The natural language query input by the user.
                  example: "Show all invoices for Acme Corp."
              required:
                - query
        required: true
      parameters:
        - name: page
          in: query
          description: The page number for pagination (default is 1).
          required: false
          schema:
            type: integer
            example: 1
        - name: page_size
          in: query
          description: The number of invoices to return per page (maximum 100).
          required: false
          schema:
            type: integer
            example: 100
        - name: sort_by
          in: query
          description: The field to sort by (e.g., 'invoice_date', 'invoice_number').
          required: false
          schema:
            type: string
            example: invoice_date
        - name: sort_order
          in: query
          description: The sorting order (either 'asc' for ascending or 'desc' for descending).
          required: false
          schema:
            type: string
            enum: [asc, desc]
            example: desc
      responses:
        '200':
          description: A successful response with the aggregated AR invoices data and dynamic insights.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sql_query:
                    type: string
                    description: The generated SQL query that was executed against the database.
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        subsidiary:
                          type: string
                          description: Alphanumeric identifier for the subsidiary (e.g., "SubsidiaryA123")
                        business_unit:
                          type: string
                          description: Business unit associated with the invoice.
                        customer_name:
                          type: string
                          description: Name of the customer.
                        invoice_number:
                          type: string
                          description: Invoice number, prefixed with "INV" (e.g., "INV123456")
                          example: "INV123456"
                        invoice_date:
                          type: string
                          format: date
                          description: The date the invoice was issued.
                        invoice_status:
                          type: string
                          enum: ["OPEN", "PAST DUE", "CLOSED"]
                          description: The status of the invoice (e.g., OPEN, PAST DUE, PAID, CLOSED).
                        invoice_due_date:
                          type: string
                          format: date
                          description: The due date of the invoice.
                        invoice_aging_bucket:
                          type: string
                          enum: ["0-30", "31-60", "61-90"]
                          description: The aging bucket for the invoice based on due date.
                        memo:
                          type: string
                          description: A memo or note associated with the invoice.
                        invoice_original_amount_local:
                          type: number
                          format: float
                          description: The original amount of the invoice in local currency.
                        invoice_original_amount_usd:
                          type: number
                          format: float
                          description: The original amount of the invoice in USD.
                        invoice_open_amount_local:
                          type: number
                          format: float
                          description: The open amount of the invoice in the local currency.
                        invoice_open_amount_usd:
                          type: number
                          format: float
                          description: The open amount of the invoice in USD.
                        invoice_due_amount_local:
                          type: number
                          format: float
                          description: The due amount of the invoice in the local currency.
                        invoice_due_amount_usd:
                          type: number
                          format: float
                          description: The due amount of the invoice in USD.
                  insights:
                    type: object
                    properties:
                      total_invoices:
                        type: integer
                        description: Total number of invoices across all pages.
                      total_due_amount_local:
                        type: number
                        format: float
                        description: Total due amount in local currency across all pages.
                      total_due_amount_usd:
                        type: number
                        format: float
                        description: Total due amount in USD across all pages.
                      invoice_status_distribution:
                        type: object
                        additionalProperties:
                          type: integer
                        description: Distribution of invoices by status (e.g., OPEN, PAST DUE, PAID, CLOSED).
                      customer_invoice_count:
                        type: object
                        description: A breakdown of the number of invoices per customer.
                        additionalProperties:
                          type: integer
                      highest_invoice_due:
                        type: object
                        properties:
                          invoice_number:
                            type: string
                          due_amount_local:
                            type: number
                            format: float
                          due_amount_usd:
                            type: number
                            format: float
                        description: Information on the highest due invoice.
                      aging_bucket_distribution:
                        type: object
                        additionalProperties:
                          type: integer
                        description: Distribution of invoices across aging buckets (e.g., "0-30 days", "31-60 days", "60-90 days").
                      total_open_amount_local:
                        type: number
                        format: float
                        description: Total open amount across all invoices in local currency.
                      total_open_amount_usd:
                        type: number
                        format: float
                        description: Total open amount across all invoices in USD.
        '400':
          description: Invalid input or missing required fields.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message describing the validation issue.
        '401':
          description: Unauthorized, invalid or missing authentication tokens.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message for unauthorized access.
        '429':
          description: Too many requests, rate limit exceeded (100 requests per minute).
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating rate limiting.
                  retry_after:
                    type: integer
                    description: Time in seconds until the client can retry.
                  limit:
                    type: integer
                    description: The maximum number of requests allowed per minute.
                    example: 100
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating the internal error.
      security:
        - BearerAuth: []
        - UserToken: []
    securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
        description: Use an API access token for authentication.
      UserToken:
        type: apiKey
        in: header
        name: x-token
        description: Use a user-specific access token for authentication.

components:
  schemas:
    Invoice:
      type: object
      properties:
        subsidiary:
          type: string
          description: Alphanumeric identifier for the subsidiary (e.g., "SubsidiaryA123")
        business_unit:
          type: string
          description: Business unit associated with the invoice.
        customer_name:
          type: string
          description: Name of the customer.
        invoice_number:
          type: string
          description: Invoice number, prefixed with "INV" (e.g., "INV123456")
        invoice_date:
          type: string
          format: date
          description: The date the invoice was issued.
        invoice_status:
          type: string
          enum: ["OPEN", "PAST DUE", "CLOSED"]
          description: The status of the invoice.
        invoice_due_date:
          type: string
          format: date
          description: The due date of the invoice.
        invoice_aging_bucket:
          type: string
          enum: ["0-30", "31-60", "61-90"]
          description: The aging bucket for the invoice based on due date.
        memo:
          type: string
          description: A memo or note associated with the invoice.
        invoice_original_amount_local:
          type: number
          format: float
          description: The original amount of the invoice in local currency.
        invoice_original_amount_usd:
          type: number
          format: float
          description: The original amount of the invoice in USD.
        invoice_open_amount_local:
          type: number
          format: float
          description: The open amount of the invoice in the local currency.
        invoice_open_amount_usd:
          type: number
          format: float
          description: The open amount of the invoice in USD.
        invoice_due_amount_local:
          type: number
          format: float
          description: The due amount of the invoice in the local currency.
        invoice_due_amount_usd:
          type: number
          format: float
          description: The due amount of the invoice in USD.
    Error:
      type: object
      properties:
        error:
          type: string
  
   RateLimitError:
   type: object
   properties:
    error:
      type: string
      description: Error message indicating rate limiting.
    retry_after:
      type: integer
      description: Time in seconds to wait before retrying the request. The client must wait for this duration before making another request.
      example: 60
    limit:
      type: integer
      description: The maximum number of requests allowed per minute.
      example: 100


  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    UserToken:
      type: apiKey
      in: header
      name: x-token
